#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

# CONNECT_PLUGIN_PATH is broken in KafkaConnect. It only loads the jar file with the
# connector class. A wround is to set CLASSPATH.
# Due to jar conflicts, /kafka/libs/* must be included first in the class path.
# Set arguments as Docker options ($@)
docker run $@ --volume $APP_DIR/padogrid:/padogrid -it --rm --name connect --network my_network -p 8083:8083 -e BOOTSTRAP_SERVERS=kafka:9092 -e CONNECT_PLUGIN_PATH=/kafka/connect,/padogrid/lib,/padogrid/plugins -e CLASSPATH=/kafka/libs/*:/padogrid/lib/*:/padogrid/plugins/* -e GROUP_ID=1 -e CONFIG_STORAGE_TOPIC=my_connect_configs -e OFFSET_STORAGE_TOPIC=my_connect_offsets -e STATUS_STORAGE_TOPIC=my_connect_statuses debezium/connect:1.0
